services:
  backend:
    build:
      context: ./backend
    container_name: weather-backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - weather-net
    volumes:
    - ./backend:/app
    - /app/node_modules

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: weather-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge
